---
- name: Parse cron schedule
  set_fact:
    minute: "{{ MONITOR_CRON_SCHEDULE.split(' ')[0] }}"
    hour: "{{ MONITOR_CRON_SCHEDULE.split(' ')[1] }}"
    day: "{{ MONITOR_CRON_SCHEDULE.split(' ')[2] }}"
    month: "{{ MONITOR_CRON_SCHEDULE.split(' ')[3] }}"
    weekday: "{{ MONITOR_CRON_SCHEDULE.split(' ')[4] }}"
    job: "/bin/bash -c 'cd {{ bridge_path }}/monitor/scripts; ./checkDocker.sh >>cronWorker.out 2>>cronWorker.err'"
  ignore_errors: True
  register: set_fact_result
- name: Add cron entry
  cron:
    name: "RUN_MONITOR_CHECKS"
    minute: "{{ minute }}"
    hour: "{{ hour }}"
    day: "{{ day }}"
    month: "{{ month }}"
    weekday: "{{ weekday }}"
    job: "{{ job }}"
  when: not set_fact_result.failed
